CREATE TABLE IF NOT EXISTS `SIGE_ADMIN` (
  `ID_ADMIN` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(128) NOT NULL,
  `PASSWORD` VARCHAR(512) NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `sige_admin_id_pk` PRIMARY KEY (`ID_ADMIN`),
  CONSTRAINT `sige_admin_username_uk` UNIQUE (`USERNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
